### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by suryaexe** [automata-tech/eva_python_sdk#108]
getting this error any help would be great:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\thebl\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\thebl\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\thebl\anaconda3\lib\site-packages\evasdk\eva_locker.py", line 84, in __renewal_timer
    self.__eva.unlock()
  File "C:\Users\thebl\anaconda3\lib\site-packages\evasdk\Eva.py", line 154, in unlock
    return self.__http_client.lock_unlock()
  File "C:\Users\thebl\anaconda3\lib\site-packages\evasdk\eva_http_client.py", line 265, in lock_unlock
    eva_error('lock_unlock error', r)
  File "C:\Users\thebl\anaconda3\lib\site-packages\evasdk\eva_errors.py", line 35, in eva_error
    __handle_http_error(label, r)
  File "C:\Users\thebl\anaconda3\lib\site-packages\evasdk\eva_errors.py", line 58, in __handle_http_error
    raise EvaServerError(error_string)
evasdk.eva_errors.EvaServerError: lock_unlock error: status code 500 with error [{'error': {'error_code': 1, 'title': 'internal server error'}}]

**Comment by Charles-Dai** [comment]
sry to bother: have your problem been solved yet? I just encountered the same error message
